# Generated by Django 3.2.9 on 2021-11-13 09:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date posted'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='time_posted',
            field=models.DateTimeField(auto_now=True, verbose_name='time posted'),
        ),
    ]
